4.8 new cards
Guyutongxue/genius-invokation pull request #8
Opened 2024-07-17 06:58 UTC by nana-nahida

连编译都过不了，不过“能写一点是一点”😗

2024-07-17 07:25 UTC, Guyutongxue commented
首先不要修改 `.since` 的版本号；它代表这张牌首次出现的版本，不是当前描述的版本

2024-07-19 09:29 UTC, Guyutongxue requested changes

2024-07-19 09:29 UTC, Guyutongxue commented on packages/data/src/cards/event/other.ts
> +  //   c.deductDamage(DamageType.Fire, 1, "my active");
使用 `.onDispose` 即可。但是这里可以直接使用 `.doSameWhenDisposed`

2024-07-19 09:29 UTC, Guyutongxue commented on packages/data/src/cards/event/other.ts
> +  // TODO ？
这个应该是用于预览的定义值，可以直接用 `.reserve();` 终止定义

2024-07-19 09:29 UTC, Guyutongxue commented on packages/data/src/characters/anemo/consecrated_flying_serpent.ts
> +  // TODO 数据源错误？
最好详细解释一下

2024-07-19 09:29 UTC, Guyutongxue commented on packages/data/src/characters/cryo/wriothesley.ts
> +// todo 数据源错误
最好详细解释一下

2024-07-19 09:29 UTC, Guyutongxue commented on packages/data/src/cards/event/other.ts
>      c.combatStatus(BonecrunchersEnergyBlockCombatStatus)
所有的这种改好的平衡性调整，就把 `@outdated` 栏删掉

2024-07-19 09:32 UTC, Guyutongxue commented on packages/data/src/cards/equipment/weapon/pole.ts
> +  .on("modifyDamage0")
然后这里麻烦你好好看一下修改技能数值的具体分设事件名，不能用 `modifyDamage0`

以及如果能跟上最新的讨论的话，把弃牌和抽牌都放到“……后”的 `damaged` / `useSkill` 而非 `modify` 里

2024-07-19 09:35 UTC, nana-nahida commented on packages/data/src/characters/cryo/wriothesley.ts
> +// todo 数据源错误
不是物理伤害，依然是冰元素伤害

2024-07-19 09:36 UTC, nana-nahida commented on packages/data/src/characters/anemo/consecrated_flying_serpent.ts
> +  // TODO 数据源错误？
同冰狼

2024-07-20 02:57 UTC, Guyutongxue approved these changes

2024-07-20 03:08 UTC, merged